# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/api/proto/ner.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'src/api/proto/ner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17src/api/proto/ner.proto\x12\x03ner\"#\n\x12ReceiptDataRequest\x12\r\n\x05items\x18\x01 \x03(\t\"F\n\x0eIngredientData\x12\x12\n\ningredient\x18\x01 \x01(\t\x12\x0e\n\x06groups\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\t\">\n\x12PredictedDataReply\x12(\n\x0bingredients\x18\x01 \x03(\x0b\x32\x13.ner.IngredientData2I\n\nPrediction\x12;\n\x07predict\x12\x17.ner.ReceiptDataRequest\x1a\x17.ner.PredictedDataReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.api.proto.ner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECEIPTDATAREQUEST']._serialized_start=32
  _globals['_RECEIPTDATAREQUEST']._serialized_end=67
  _globals['_INGREDIENTDATA']._serialized_start=69
  _globals['_INGREDIENTDATA']._serialized_end=139
  _globals['_PREDICTEDDATAREPLY']._serialized_start=141
  _globals['_PREDICTEDDATAREPLY']._serialized_end=203
  _globals['_PREDICTION']._serialized_start=205
  _globals['_PREDICTION']._serialized_end=278
# @@protoc_insertion_point(module_scope)
